<?php

use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         $data = [
            'manufacturer' => (object)[
                'value'    => 'Iphone',
                'name'     => 'Hãng sản xuất'
            ],
            'size'       => (object)[
                'value'  => '5.7inch',
                'name'   => 'kích cỡ'
            ],
            'internalmemory' => (object)[
                'value'  => '64GB',
                'name'   => 'Bộ nhớ trong'
            ],
            'ram'        => (object)[
                'value'  => '16GB',
                'name'   => 'Ram'
            ],
            'weight'     => (object)[
                'value'  => '200gram',
                'name'   => 'Khối lượng'
            ],
            'sim'        => (object)[
                'value'  => 'etc',
                'name'   => 'Sim'
            ],
            'screen'     => (object)[
                'value'  => 'full HD',
                'name'   => 'Màn hình'
            ],
            'screensize'        => (object)[
                'value'  => '12x24',
                'name'   => 'Kích cỡ màn hình'
            ],
            'screenresolution'  => (object)[
                'value'  => 'Full HD',
                'name'   => 'Độ phân giải'
            ],
            'operatingsystem'   => (object)[
                'value' => 'IOS 14',
                'name'  => 'Hệ điều hành'
            ],
            'pin'       => (object)[
                'value' => '5000mA',
                'name'  => 'pin'
            ]
        ];
        $content = "iPhone 11 chính hãng VN/A – Chiếc điện thoại nhiều màu sắc, camera nâng cấp
        iPhone 11 là model có nhiều màu sắc nhất và có giá rẻ nhất trong bộ 3 iPhone 11 series được Apple ra mắt trong năm 2019. Bên cạnh đó, cấu hình iPhone 11 cũng được nâng cấp đặc biệt về cụm camera sau và Face ID, viên pin dung lượng lớn hơn.       
        Đa dạng sự lựa chọn với 6 phiên bản màu sắc
        Điểm nổi bật của iPhone 11 2019 đó là bên cạnh hai phiên bản đen và trắng quen thuộc thì máy còn có thêm bốn phiên bản khác đó là tím, vàng, xanh lá, đỏ. Với tất cả các phiên bản, bao gồm cả điện thoại iPhone 12 sắp ra mắt thì Apple đều thiết kế cạnh bên trùng màu với thân máy, tạo nên một thể thống nhất.";
        $description = 'iPhone 11 chính hãng VN/A – Chiếc điện thoại nhiều màu sắc, camera nâng cấp';
        
        DB::table('product')->insert([
            array(
                'title' => 'iPhone 12 Pro Chính Hãng (VN/A)',
                'slug' => \Str::slug('iPhone 12 Pro Chính Hãng (VN/A)'),
                'sku' => 'IP01',
                'price_sale' => 19900000,
                'price' => 21000000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4],                
                'option' => $data,
                'content' => $content,
                'category_id' => 2,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'iPhone 11 Chính hãng (VN/A)',
                'slug' => \Str::slug('iPhone 11 Chính hãng (VN/A)'),
                'sku' => 'IP02',
                'price_sale' => 17700000,
                'price' => 20000000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 2,
                'category_id' => 2,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'iPhone 12 Pro Max Chính Hãng (VN/A)',
                'slug' => \Str::slug('iPhone 12 Pro Max Chính Hãng (VN/A)'),
                'sku' => 'IP03',
                'price_sale' => 32490000,
                'price' => 33990000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 3,
                'category_id' => 1,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'iPhone 11 Pro Max Chính hãng (VN/A)',
                'slug' => \Str::slug('iPhone 11 Pro Max Chính hãng (VN/A)'),
                'sku' => 'IP04',
                'price_sale' => 27200000,
                'price' => 29500000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 4,
                'category_id' => 1,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'iPhone 12 Mini Chính hãng (VN/A)',
                'slug' => \Str::slug('iPhone 12 Mini Chính hãng (VN/A)'),
                'sku' => 'IP05',
                'price_sale' => 24490000,
                'price' => 21900000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 5,
                'category_id' => 1,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Apple iPhone XR 64GB Chính hãng (VN/A)',
                'slug' => \Str::slug('Apple iPhone XR 64GB Chính hãng (VN/A)'),
                'sku' => 'IP06',
                'price_sale' => 12900000,
                'price' => 14900000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 6,
                'category_id' => 1,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'iPhone 11 Pro Chính hãng (VN/A)',
                'slug' => \Str::slug('iPhone 11 Pro Chính hãng (VN/A)'),
                'sku' => 'IP07',
                'price_sale' => 23700000,
                'price' => 27000000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 7,
                'category_id' => 1,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'iPhone 11 128GB Chính hãng (VN/A)',
                'slug' => \Str::slug('iPhone 11 128GB Chính hãng (VN/A)'),
                'sku' => 'IP08',
                'price_sale' => 19600000,
                'price' => 21500000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 8,
                'category_id' => 1,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Apple iPhone 8 Plus 128GB Chính hãng (mã VN/A)',
                'slug' => \Str::slug('Apple iPhone 8 Plus 128GB Chính hãng (mã VN/A)'),
                'sku' => 'IP09',
                'price_sale' => 13000000,
                'price' => 16000000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 9,
                'category_id' => 1,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'iPhone SE 2020 Chính hãng VN/A',
                'slug' => \Str::slug('iPhone SE 2020 Chính hãng VN/A'),
                'sku' => 'IP10',
                'price_sale' => 10850000,
                'price' => 12990000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 1,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Samsung Galaxy A71',
                'slug' => \Str::slug('Samsung Galaxy A71'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 2,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Samsung Galaxy Note 10 Lite',
                'slug' => \Str::slug('Samsung Galaxy Note 10 Lite'),
                'sku' => 'SM02',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 2,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Samsung Galaxy Note 20 Ultra',
                'slug' => \Str::slug('Samsung Galaxy Note 20 Ultra'),
                'sku' => 'SM03',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 2,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Samsung Galaxy Note 10+ (Plus)',
                'slug' => \Str::slug('Samsung Galaxy Note 10+ (Plus)'),
                'sku' => 'SM04',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 2,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Samsung Galaxy Note 10',
                'slug' => \Str::slug('Samsung Galaxy Note 10'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 2,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Samsung Galaxy Note 20',
                'slug' => \Str::slug('Samsung Galaxy Note 20'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 2,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Samsung Galaxy A51',
                'slug' => \Str::slug('Samsung Galaxy A51'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 2,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Samsung Galaxy A21s',
                'slug' => \Str::slug('Samsung Galaxy A21s'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 2,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Samsung Galaxy Note 20 Ultra 5G',
                'slug' => \Str::slug('Samsung Galaxy Note 20 Ultra 5G'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 2,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Oppo Reno4',
                'slug' => \Str::slug('Oppo Reno4'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 3,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Oppo A92',
                'slug' => \Str::slug('Oppo A92'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 3,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Oppo A53',
                'slug' => \Str::slug('Oppo A53'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 3,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Oppo Reno4 Pro',
                'slug' => \Str::slug('Oppo Reno4 Pro'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 3,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Oppo Find X2',
                'slug' => \Str::slug('Oppo Find X2'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 3,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'OPPO A93',
                'slug' => \Str::slug('OPPO A93'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 3,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Oppo Reno 2F',
                'slug' => \Str::slug('Oppo Reno 2F'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 3,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Oppo Reno 3',
                'slug' => \Str::slug('Oppo Reno 3'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 3,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'OPPO A12 3GB',
                'slug' => \Str::slug('OPPO A12 3GB'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 3,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Oppo A52',
                'slug' => \Str::slug('Oppo A52'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 3,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Xiaomi Redmi Note 9 Pro',
                'slug' => \Str::slug('Xiaomi Redmi Note 9 Pro'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 4,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Xiaomi Redmi 9',
                'slug' => \Str::slug('Xiaomi Redmi 9'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 4,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Xiaomi Redmi Note 9 Pro 128GB',
                'slug' => \Str::slug('Xiaomi Redmi Note 9 Pro 128GB'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 4,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Xiaomi Redmi 9C 3GB - 64GB',
                'slug' => \Str::slug('Xiaomi Redmi 9C 3GB - 64GB'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 4,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Xiaomi Mi 10T Pro',
                'slug' => \Str::slug('Xiaomi Mi 10T Pro'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 4,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Xiaomi Mi Note 10',
                'slug' => \Str::slug('Xiaomi Mi Note 10'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 4,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Xiaomi Mi Note 10 Lite',
                'slug' => \Str::slug('Xiaomi Mi Note 10 Lite'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 4,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Xiaomi Redmi Note 9s 4G 64GB',
                'slug' => \Str::slug('Xiaomi Redmi Note 9s 4G 64GB'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 4,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Xiaomi Redmi Note 9',
                'slug' => \Str::slug('Xiaomi Redmi Note 9'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 4,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Xiaomi POCO X3 NFC 128GB',
                'slug' => \Str::slug('Xiaomi POCO X3 NFC 128GB'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 4,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vivo V20',
                'slug' => \Str::slug('Vivo V20'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 5,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vivo Y50',
                'slug' => \Str::slug('Vivo Y50'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 5,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vivo V19',
                'slug' => \Str::slug('Vivo V19'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 5,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vivo Y20',
                'slug' => \Str::slug('Vivo Y20'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 5,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vivo Y20',
                'slug' => \Str::slug('Vivo Y20'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 5,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vivo Y11',
                'slug' => \Str::slug('Vivo Y11'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 5,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vivo Y30',
                'slug' => \Str::slug('Vivo Y30'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 5,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vivo Y19 6GB',
                'slug' => \Str::slug('Vivo Y19 6GB'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 5,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vivo U10',
                'slug' => \Str::slug('Vivo U10'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 5,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Realme 6i',
                'slug' => \Str::slug('Realme 6i'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 6,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Realme C12',
                'slug' => \Str::slug('Realme C12'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 6,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Realme 6 8GB',
                'slug' => \Str::slug('Realme 6 8GB'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 6,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Realme 6',
                'slug' => \Str::slug('Realme 6'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 6,'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Realme 5i',
                'slug' => \Str::slug('Realme 5i'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 6,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Realme C3',
                'slug' => \Str::slug('Realme C3'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 6,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Realme C11',
                'slug' => \Str::slug('Realme C11'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 6,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Realme 7i',
                'slug' => \Str::slug('Realme 7i'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 6,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Realme 6 Pro',
                'slug' => \Str::slug('Realme 6 Pro'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 6,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Realme C3i',
                'slug' => \Str::slug('Realme C3i'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 6,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vsmart Active 3 6GB Ram',
                'slug' => \Str::slug('Vsmart Active 3 6GB Ram'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 8,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vsmart Bee 3',
                'slug' => \Str::slug('Vsmart Bee 3'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 8,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vsmart Joy 3 4GB',
                'slug' => \Str::slug('Vsmart Joy 3 4GB'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 8,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vsmart Aris 6G 64GB',
                'slug' => \Str::slug('Vsmart Aris 6G 64GB'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 8,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vsmart Live 4',
                'slug' => \Str::slug('Vsmart Live 4'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 8,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vsmart Joy 3 2GB',
                'slug' => \Str::slug('Vsmart Joy 3 2GB'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 8,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vsmart Joy 4',
                'slug' => \Str::slug('Vsmart Joy 4'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 8,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vsmart Aris Pro 4G',
                'slug' => \Str::slug('Vsmart Aris Pro 4G'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 8,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vsmart Active 3 4GB Ram',
                'slug' => \Str::slug('Vsmart Active 3 4GB Ram'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 8,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vsmart Joy 4 4GB',
                'slug' => \Str::slug('Vsmart Joy 4 4GB'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 8,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Nokia 8.3 5G',
                'slug' => \Str::slug('Nokia 8.3 5G'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 9,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Nokia 5.3',
                'slug' => \Str::slug('Nokia 5.3'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 9,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Nokia 2.4',
                'slug' => \Str::slug('Nokia 2.4'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 9,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Nokia C2',
                'slug' => \Str::slug('Nokia C2'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 9,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Nokia 7.2',
                'slug' => \Str::slug('Nokia 7.2'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 9,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Vsmart',
                'slug' => \Str::slug('Vsmart'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 9,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Nokia 800 Tough',
                'slug' => \Str::slug('Nokia 800 Tough'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 9,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Nokia 2720 Flip',
                'slug' => \Str::slug('Nokia 2720 Flip'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 9,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Nokia 2.3',
                'slug' => \Str::slug('Nokia 2.3'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 9,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            ),
            array(
                'title' => 'Nokia 2.2',
                'slug' => \Str::slug('Nokia 2.2'),
                'sku' => 'SM01',
                'price_sale' => 8000000,
                'price' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => [1,2,3,4], 
                'category_id' => 9,
                'option' => $data,
                'content' => $content,
                'description' => $description,
                'avatar_id' => 1
            )
        ]);
    }
}
