<?php

use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product')->insert([
            array(
                'title' => 'iPhone 12 Pro Chính Hãng (VN/A)',
                'slug' => \Str::slug('iPhone 12 Pro Chính Hãng (VN/A)'),
                'sku' => 'IP01',
                'price' => 19900000,
                'price_sale' => 21000000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 1,
                'category_id' => 1,
            ),
            array(
                'title' => 'iPhone 11 Chính hãng (VN/A)',
                'slug' => \Str::slug('iPhone 11 Chính hãng (VN/A)'),
                'sku' => 'IP02',
                'price' => 17700000,
                'price_sale' => 20000000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 2,
                'category_id' => 1,
            ),
            array(
                'title' => 'iPhone 12 Pro Max Chính Hãng (VN/A)',
                'slug' => \Str::slug('iPhone 12 Pro Max Chính Hãng (VN/A)'),
                'sku' => 'IP03',
                'price' => 32490000,
                'price_sale' => 33990000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 3,
                'category_id' => 1,
            ),
            array(
                'title' => 'iPhone 11 Pro Max Chính hãng (VN/A)',
                'slug' => \Str::slug('iPhone 11 Pro Max Chính hãng (VN/A)'),
                'sku' => 'IP04',
                'price' => 27200000,
                'price_sale' => 29500000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 4,
                'category_id' => 1,
            ),
            array(
                'title' => 'iPhone 12 Mini Chính hãng (VN/A)',
                'slug' => \Str::slug('iPhone 12 Mini Chính hãng (VN/A)'),
                'sku' => 'IP05',
                'price' => 24490000,
                'price_sale' => 21900000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 5,
                'category_id' => 1,
            ),
            array(
                'title' => 'Apple iPhone XR 64GB Chính hãng (VN/A)',
                'slug' => \Str::slug('Apple iPhone XR 64GB Chính hãng (VN/A)'),
                'sku' => 'IP06',
                'price' => 12900000,
                'price_sale' => 14900000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 6,
                'category_id' => 1,
            ),
            array(
                'title' => 'iPhone 11 Pro Chính hãng (VN/A)',
                'slug' => \Str::slug('iPhone 11 Pro Chính hãng (VN/A)'),
                'sku' => 'IP07',
                'price' => 23700000,
                'price_sale' => 27000000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 7,
                'category_id' => 1,
            ),
            array(
                'title' => 'iPhone 11 128GB Chính hãng (VN/A)',
                'slug' => \Str::slug('iPhone 11 128GB Chính hãng (VN/A)'),
                'sku' => 'IP08',
                'price' => 19600000,
                'price_sale' => 21500000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 8,
                'category_id' => 1,
            ),
            array(
                'title' => 'Apple iPhone 8 Plus 128GB Chính hãng (mã VN/A)',
                'slug' => \Str::slug('Apple iPhone 8 Plus 128GB Chính hãng (mã VN/A)'),
                'sku' => 'IP09',
                'price' => 13000000,
                'price_sale' => 16000000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 9,
                'category_id' => 1,
            ),
            array(
                'title' => 'iPhone SE 2020 Chính hãng VN/A',
                'slug' => \Str::slug('iPhone SE 2020 Chính hãng VN/A'),
                'sku' => 'IP10',
                'price' => 10850000,
                'price_sale' => 12990000,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 1,
            ),
            array(
                'title' => 'Samsung Galaxy A71',
                'slug' => \Str::slug('Samsung Galaxy A71'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 2,
            ),
            array(
                'title' => 'Samsung Galaxy Note 10 Lite',
                'slug' => \Str::slug('Samsung Galaxy Note 10 Lite'),
                'sku' => 'SM02',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 2,
            ),
            array(
                'title' => 'Samsung Galaxy Note 20 Ultra',
                'slug' => \Str::slug('Samsung Galaxy Note 20 Ultra'),
                'sku' => 'SM03',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 2,
            ),
            array(
                'title' => 'Samsung Galaxy Note 10+ (Plus)',
                'slug' => \Str::slug('Samsung Galaxy Note 10+ (Plus)'),
                'sku' => 'SM04',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 2,
            ),
            array(
                'title' => 'Samsung Galaxy Note 10',
                'slug' => \Str::slug('Samsung Galaxy Note 10'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 2,
            ),
            array(
                'title' => 'Samsung Galaxy Note 20',
                'slug' => \Str::slug('Samsung Galaxy Note 20'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 2,
            ),
            array(
                'title' => 'Samsung Galaxy A51',
                'slug' => \Str::slug('Samsung Galaxy A51'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 2,
            ),
            array(
                'title' => 'Samsung Galaxy A21s',
                'slug' => \Str::slug('Samsung Galaxy A21s'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 2,
            ),
            array(
                'title' => 'Samsung Galaxy Note 20 Ultra 5G',
                'slug' => \Str::slug('Samsung Galaxy Note 20 Ultra 5G'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 2,
            ),
            array(
                'title' => 'Oppo Reno4',
                'slug' => \Str::slug('Oppo Reno4'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 3,
            ),
            array(
                'title' => 'Oppo A92',
                'slug' => \Str::slug('Oppo A92'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 3,
            ),
            array(
                'title' => 'Oppo A53',
                'slug' => \Str::slug('Oppo A53'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 3,
            ),
            array(
                'title' => 'Oppo Reno4 Pro',
                'slug' => \Str::slug('Oppo Reno4 Pro'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 3,
            ),
            array(
                'title' => 'Oppo Find X2',
                'slug' => \Str::slug('Oppo Find X2'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 3,
            ),
            array(
                'title' => 'OPPO A93',
                'slug' => \Str::slug('OPPO A93'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 3,
            ),
            array(
                'title' => 'Oppo Reno 2F',
                'slug' => \Str::slug('Oppo Reno 2F'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 3,
            ),
            array(
                'title' => 'Oppo Reno 3',
                'slug' => \Str::slug('Oppo Reno 3'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 3,
            ),
            array(
                'title' => 'OPPO A12 3GB',
                'slug' => \Str::slug('OPPO A12 3GB'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 3,
            ),
            array(
                'title' => 'Oppo A52',
                'slug' => \Str::slug('Oppo A52'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 3,
            ),
            array(
                'title' => 'Xiaomi Redmi Note 9 Pro',
                'slug' => \Str::slug('Xiaomi Redmi Note 9 Pro'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 4,
            ),
            array(
                'title' => 'Xiaomi Redmi 9',
                'slug' => \Str::slug('Xiaomi Redmi 9'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 4,
            ),
            array(
                'title' => 'Xiaomi Redmi Note 9 Pro 128GB',
                'slug' => \Str::slug('Xiaomi Redmi Note 9 Pro 128GB'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 4,
            ),
            array(
                'title' => 'Xiaomi Redmi 9C 3GB - 64GB',
                'slug' => \Str::slug('Xiaomi Redmi 9C 3GB - 64GB'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 4,
            ),
            array(
                'title' => 'Xiaomi Mi 10T Pro',
                'slug' => \Str::slug('Xiaomi Mi 10T Pro'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 4,
            ),
            array(
                'title' => 'Xiaomi Mi Note 10',
                'slug' => \Str::slug('Xiaomi Mi Note 10'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 4,
            ),
            array(
                'title' => 'Xiaomi Mi Note 10 Lite',
                'slug' => \Str::slug('Xiaomi Mi Note 10 Lite'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 4,
            ),
            array(
                'title' => 'Xiaomi Redmi Note 9s 4G 64GB',
                'slug' => \Str::slug('Xiaomi Redmi Note 9s 4G 64GB'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 4,
            ),
            array(
                'title' => 'Xiaomi Redmi Note 9',
                'slug' => \Str::slug('Xiaomi Redmi Note 9'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 4,
            ),
            array(
                'title' => 'Xiaomi POCO X3 NFC 128GB',
                'slug' => \Str::slug('Xiaomi POCO X3 NFC 128GB'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 4,
            ),
            array(
                'title' => 'Vivo V20',
                'slug' => \Str::slug('Vivo V20'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 5,
            ),
            array(
                'title' => 'Vivo Y50',
                'slug' => \Str::slug('Vivo Y50'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 5,
            ),
            array(
                'title' => 'Vivo V19',
                'slug' => \Str::slug('Vivo V19'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 5,
            ),
            array(
                'title' => 'Vivo Y20',
                'slug' => \Str::slug('Vivo Y20'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 5,
            ),
            array(
                'title' => 'Vivo Y20',
                'slug' => \Str::slug('Vivo Y20'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 5,
            ),
            array(
                'title' => 'Vivo Y11',
                'slug' => \Str::slug('Vivo Y11'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 5,
            ),
            array(
                'title' => 'Vivo Y30',
                'slug' => \Str::slug('Vivo Y30'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 5,
            ),
            array(
                'title' => 'Vivo Y19 6GB',
                'slug' => \Str::slug('Vivo Y19 6GB'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 5,
            ),
            array(
                'title' => 'Vivo U10',
                'slug' => \Str::slug('Vivo U10'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 5,
            ),
            array(
                'title' => 'Realme 6i',
                'slug' => \Str::slug('Realme 6i'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 6,
            ),
            array(
                'title' => 'Realme C12',
                'slug' => \Str::slug('Realme C12'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 6,
            ),
            array(
                'title' => 'Realme 6 8GB',
                'slug' => \Str::slug('Realme 6 8GB'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 6,
            ),
            array(
                'title' => 'Realme 6',
                'slug' => \Str::slug('Realme 6'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 6,
            ),
            array(
                'title' => 'Realme 5i',
                'slug' => \Str::slug('Realme 5i'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 6,
            ),
            array(
                'title' => 'Realme C3',
                'slug' => \Str::slug('Realme C3'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 6,
            ),
            array(
                'title' => 'Realme C11',
                'slug' => \Str::slug('Realme C11'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 6,
            ),
            array(
                'title' => 'Realme 7i',
                'slug' => \Str::slug('Realme 7i'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 6,
            ),
            array(
                'title' => 'Realme 6 Pro',
                'slug' => \Str::slug('Realme 6 Pro'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 6,
            ),
            array(
                'title' => 'Realme C3i',
                'slug' => \Str::slug('Realme C3i'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 6,
            ),
            array(
                'title' => 'Vsmart Active 3 6GB Ram',
                'slug' => \Str::slug('Vsmart Active 3 6GB Ram'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 8,
            ),
            array(
                'title' => 'Vsmart Bee 3',
                'slug' => \Str::slug('Vsmart Bee 3'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 8,
            ),
            array(
                'title' => 'Vsmart Joy 3 4GB',
                'slug' => \Str::slug('Vsmart Joy 3 4GB'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 8,
            ),
            array(
                'title' => 'Vsmart Aris 6G 64GB',
                'slug' => \Str::slug('Vsmart Aris 6G 64GB'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 8,
            ),
            array(
                'title' => 'Vsmart Live 4',
                'slug' => \Str::slug('Vsmart Live 4'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 8,
            ),
            array(
                'title' => 'Vsmart Joy 3 2GB',
                'slug' => \Str::slug('Vsmart Joy 3 2GB'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 8,
            ),
            array(
                'title' => 'Vsmart Joy 4',
                'slug' => \Str::slug('Vsmart Joy 4'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 8,
            ),
            array(
                'title' => 'Vsmart Aris Pro 4G',
                'slug' => \Str::slug('Vsmart Aris Pro 4G'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 8,
            ),
            array(
                'title' => 'Vsmart Active 3 4GB Ram',
                'slug' => \Str::slug('Vsmart Active 3 4GB Ram'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 8,
            ),
            array(
                'title' => 'Vsmart Joy 4 4GB',
                'slug' => \Str::slug('Vsmart Joy 4 4GB'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 8,
            ),
            array(
                'title' => 'Nokia 8.3 5G',
                'slug' => \Str::slug('Nokia 8.3 5G'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 9,
            ),
            array(
                'title' => 'Nokia 5.3',
                'slug' => \Str::slug('Nokia 5.3'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 9,
            ),
            array(
                'title' => 'Nokia 2.4',
                'slug' => \Str::slug('Nokia 2.4'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 9,
            ),
            array(
                'title' => 'Nokia C2',
                'slug' => \Str::slug('Nokia C2'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 9,
            ),
            array(
                'title' => 'Nokia 7.2',
                'slug' => \Str::slug('Nokia 7.2'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 9,
            ),
            array(
                'title' => 'Vsmart',
                'slug' => \Str::slug('Vsmart'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 9,
            ),
            array(
                'title' => 'Nokia 800 Tough',
                'slug' => \Str::slug('Nokia 800 Tough'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 9,
            ),
            array(
                'title' => 'Nokia 2720 Flip',
                'slug' => \Str::slug('Nokia 2720 Flip'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 9,
            ),
            array(
                'title' => 'Nokia 2.3',
                'slug' => \Str::slug('Nokia 2.3'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 9,
            ),
            array(
                'title' => 'Nokia 2.2',
                'slug' => \Str::slug('Nokia 2.2'),
                'sku' => 'SM01',
                'price' => 8000000,
                'price_sale' => 10490000 ,
                'qty' => 100,
                'weight' => 1,
                'height' => 1,
                'width' => 1,
                'media_id' => 10,
                'category_id' => 9,
            )
        ]);
    }
}
